language: python

python:
  - "3.6"

cache:
  directories:
    - $HOME/.cache
    - $HOME/girder_build/store
    - $HOME/girder_build/data

before_install:
  # Fix a travis/boto issue.  See
  # https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg

  - GIRDER_VERSION=2.x-maintenance
  - GIRDER_PATH=$HOME/girder/girder
  - GIRDER_BUILD_PATH=$HOME/girder_build
  - SLICER_CLI_WEB_VERSION=master
  - COLORMAPS_PATH=$TRAVIS_BUILD_DIR

  - mkdir -p $HOME/.cache/node_modules || true
  - ln -sf $HOME/.cache/node_modules .
  - nvm install v8
  - npm install -g npm
  - npm install -g npm-install-retry
  - npm --version
  - npm prune

  - git clone https://github.com/girder/girder.git $GIRDER_PATH && git -C $GIRDER_PATH checkout $GIRDER_VERSION
  - CACHE=$HOME/.cache CMAKE_VERSION=3.4.3 CMAKE_SHORT_VERSION=3.4 source $GIRDER_PATH/scripts/install_cmake.sh
  - cmake --version

  - slicer_cli_web_path=$girder_path/plugins/slicer_cli_web
  - git clone https://github.com/girder/slicer_cli_web.git $slicer_cli_web_path && git -C $slicer_cli_web_path checkout $SLICER_CLI_WEB_VERSION

  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export MONGO_VERSION=3.6.2; else export MONGO_VERSION=3.4.10; fi
  - CACHE=$HOME/.cache source $GIRDER_PATH/scripts/install_mongo.sh
  - mkdir /tmp/db
  - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
  - mongod --version

install:
  - pushd $GIRDER_PATH
  - pip install --no-cache-dir -U -r requirements-dev.txt -e .[mount]
  - pip install -U --upgrade-strategy eager -r $slicer_cli_web_path/requirements.txt
  - popd

  - girder-install plugin --symlink $COLORMAPS_PATH
  - ls -l $GIRDER_PATH/plugins

  - npm-install-retry
  - girder-install web --plugins=slicer_cli_web,colormaps --dev

script:
  - mkdir -p $GIRDER_BUILD_PATH
  - cd $GIRDER_BUILD_PATH
  - cmake -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} -DRUN_CORE_TESTS:BOOL="OFF" -DTEST_PLUGINS:STRING="colormaps" $GIRDER_PATH
  - make -j 3
  - JASMINE_TIMEOUT=15000 ctest -VV

after_success:
  - bash <(curl -s https://codecov.io/bash) -R $COLORMAPS_PATH -s $GIRDER_PATH
